### ISSUE TITLE
Project fails to build with default installation of ODPI in Linux

### ISSUE THREAD

**Issue by apkhandkar** [haskell-oracle/oracle-simple#30]
From `oracle-simple.cabal`:
```cabal
  if flag(default_paths) && os(linux)
    includes:
      /opt/oracle/include/dpi.h
    include-dirs:
      /opt/oracle/include
    extra-lib-dirs:
      /opt/oracle/lib
```
From the ODPI Makefile:
```makefile
PREFIX ?= /usr/local
INSTALL_LIB_DIR = $(PREFIX)/lib
INSTALL_INC_DIR = $(PREFIX)/include
INSTALL_SHARE_DIR = $(PREFIX)/share/odpi
```
A default installation of ODPI in Linux would place the headers and library files under `/usr/local`, not `/opt/oracle`. One would have to set `env PREFIX=/opt/oracle` while installing ODPI to make the project build in Linux.

**Comment by dmjio** [comment]
https://github.com/haskell-oracle/oracle-simple/commit/dd4e10fc6cf591221133a0e1b42f0ab7041df4ba
